package com.quadratic.main;

/**
 * A class used to test the
 * functionality of the Quadratic class.
 * 
 * Date: 9-22-14
 * 
 * @author Ryan Hochmuth & Jason Griffith
 *
 */
public class QuadTest 
{
	/***********************
	 * Quadratics
	 **********************/
	Quadratic quad1;
	Quadratic quad2;
	// quad3 is the sum of quad1 and quad2
	Quadratic quad3;
	
	/**
	 * Gives a description of what
	 * the program is doing.
	 */
	public void intro()
	{
		
	}
	
	/**
	 * 
	 * Does the required calculation, 
	 * creates a clone of the first quadratic,
	 * checks if they are aliases, then checks 
	 * if the two quadratics have the same coefficients. 
	 */
	public static void  calculations()
	{
		//double a = Quadratic.getCoefA();
		//double b = Quadratic.getCoefB();
		//double c = Quadratic.getCoefC();
		
		//double quadPlusResult = (-b + (Math.sqrt((b*b - ((4 * a * c))))))/ (2 * a);
		//double quadNegResult = (-b - (Math.sqrt((b*b - ((4 * a * c))))))/ (2 * a);
	}
	
	/**
	 * Parses a String line into
	 * Separate tokens.
	 * @param line - The input String
	 */
	public static void parse(String line)
	{
		System.out.println(line);
	}
	
	/**
	 * Create the output of information
	 * generated by this program.
	 */
	public void output()
	{
		
	}
}
